console:

  - name: architek
    namespace: core.kernel.console.commands
    class: ArchitekCommand
    description: Architek Framework - Python

  - name: test
    namespace: core.kernel.console.commands
    class: TestCommand
    description: Architek Framework - Python

  - name: start
    namespace: core.kernel.console.commands
    class: StartCommand
    description: Start the application

  - name: help
    namespace: core.kernel.console.commands
    class: HelpCommand
    description: Get list of commands

  - name: make:command
    namespace: core.kernel.console.commands.make
    class: MakeCommandCommand
    description: Create a new Command Class

  - name: make:service
    namespace: core.kernel.console.commands.make
    class: MakeServiceCommand
    description: Create a new Service Class

  - name: key:generate
    namespace: core.kernel.console.commands.key
    class: KeyGenerateCommand
    description: Generate Key for your application

  - name: key:show
    namespace: core.kernel.console.commands.key
    class: KeyShowCommand
    description: Show the application key

  - name: cache:clear
    namespace: core.kernel.console.commands.cache
    class: CacheClearCommand
    description: Clear application cache

  - name: database:create
    description: Create database
    namespace: core.kernel.console.commands.database
    class: DatabaseCreateCommand
    arguments:
      - short: s
        long: seed
        required: false
        value: { type: boolean, default: false }

  - name: database:drop
    namespace: core.kernel.console.commands.database
    class: DatabaseDropCommand
    description: Drop database

  - name: schema:update
    namespace: core.kernel.console.commands.schema
    class: SchemaUpdateCommand
    description: Create database, generate entity, seed database

  - name: database:recreate
    namespace: core.kernel.console.commands.database
    class: DatabaseRecreateCommand
    description: Recreate database
    arguments:
      - short: s
        long: seed
        required: false
        value: { type: boolean, default: false }

  - name: database:seed
    namespace: core.kernel.console.commands.database
    class: DatabaseSeedCommand
    description: Seed database
    arguments:
      - short: s
        long: seed
        required: false
        value: { type: boolean, default: false }

  - name: entity:generate
    namespace: core.kernel.console.commands.entity
    class: EntityGenerateCommand
    description: Generate entity classes from database schema
    arguments:
      - short: f
        long: force
        required: false
        value: { type: boolean, default: false }