from core.orm.entity.BaseEntity import BaseEntity


class User(BaseEntity):

    """
        User - Generated by Architek

        - Fields :
            - id: int
            - name: str
            - email: str
            - password: str
    """

    def __init__(self, name: str, email: str, password: str):
        super().__init__("id")
        self.name = name
        self.email = email
        self.password = password
