app:

  name: "crypto-trading"
  version: "indev-0"
  description: "Automated ai-driven crypto trading bot"
  env: "development" # development | production

  use:
    orm: false
    http_server: true