commands: []

#    - name: test
#      description: Test command
#      namespace: app.commands
#      class: TestCommand
#      arguments:
#        - short: t
#          long: test
#          required: false
#          value: { type: boolean, default: false }