console:

  commands:

#    - name: database:create
#      description: Create database
#      namespace: app.commands
#      class: DatabaseCreateCommand
#      arguments:
#        - short: s
#          long: seed
#          required: false
#          value: { type: boolean, default: false }