commands:

    - name: login
      description: Test command
      namespace: app.commands
      class: TestCommand
      arguments:
        - short: s
          long: seed
          required: false
          value: { type: boolean, default: false }