logs:

  output:
    type: [file, console] # [] -> file|console
    prefix: "[{date}] [{channel}] [{file}:{line}] {message}"
    date: "Y-m-d H:i:s"

  file:
    path: /storage/logs
    name: app.log
    compress: true

  channels:

    #  subscribe to these channels :
    #  info, debug, warning, error
    #  use * to subscribe to all channels

    development:
      file: ["*"]
      console: ["*"]

    production:
      file: ["info", "error"]
      console: ["info", "error"]
