from core.orm.entity.BaseEntity import BaseEntity
from app.common.entity.User import User


class Project(BaseEntity):

    """
        Project - Generated by Architek

        - Fields :
            - id: int
            - name: str
            - user: User
    """

    def __init__(self, name: str, user: User):
        super().__init__("id")
        self.name = name
        self.user = user
