entity:

  name: Project
  table: project
  timestamp: true
  key: { name: id, generator: autoincrement } # or { name: uuid, generator: uuid } or { name: my_row, generator: custom }
  fields:
    - id: { type: integer, primary: true, autoincrement: true }
    - name: { type: string, length: 255 }
    - user: { type: relation, entity: user, field: id, reference: user_id, relation: many_to_one }